jobs:
  lint:
    uses: githubabcs/gh-abcs-actions/.github/workflows/super-linter.yml@main

  ci_windows_node12:
    name: CI on Windows with Node 12
    runs-on: windows-2019
    needs: lint
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 12
      - name: Run test suite
        run: |
          echo npm ci
          echo npm run build --if-present
          echo npm test
      - shell: bash
        run: |
          echo 'Test upload artifact' > output.log
      - name: Upload output file
        uses: actions/upload-artifact@v2
        with:
          name: output-log-file
          path: output.log

  ci_ubuntu2004_node12:
    name: CI on Windows with Node 12
    runs-on: ubuntu-20.04
    needs: lint
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 12
      - name: Run test suite
        run: |
          echo npm ci
          echo npm run build --if-present
          echo npm test
      - shell: bash
        run: |
          echo 'Test upload artifact' > output.log
      - name: Upload output file
        uses: actions/upload-artifact@v2
        with:
          name: output-log-file
          path: output.log

  ci_ubuntu2204_node12:
    name: CI on Windows with Node 12
    runs-on: ubuntu-22.04
    needs: lint
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 12
      - name: Run test suite
        run: |
          echo npm ci
          echo npm run build --if-present
          echo npm test
      - shell: bash
        run: |
          echo 'Test upload artifact' > output.log
      - name: Upload output file
        uses: actions/upload-artifact@v2
        with:
          name: output-log-file
          path: output.log

  ci_macos_node12:
    name: CI on Windows with Node 12
    runs-on: macos-latest
    needs: lint
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 12
      - name: Run test suite
        run: |
          echo npm ci
          echo npm run build --if-present
          echo npm test
      - shell: bash
        run: |
          echo 'Test upload artifact' > output.log
      - name: Upload output file
        uses: actions/upload-artifact@v2
        with:
          name: output-log-file
          path: output.log

  ci_windows_node14:
    name: CI on Windows with Node 14
    runs-on: windows-2019
    needs: lint
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 14
      - name: Run test suite
        run: |
          echo npm ci
          echo npm run build --if-present
          echo npm test
      - shell: bash
        run: |
          echo 'Test upload artifact' > output.log
      - name: Upload output file
        uses: actions/upload-artifact@v2
        with:
          name: output-log-file
          path: output.log

  ci_ubuntu2004_node14:
    name: CI on Windows with Node 14
    runs-on: ubuntu-20.04
    needs: lint
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 14
      - name: Run test suite
        run: |
          echo npm ci
          echo npm run build --if-present
          echo npm test
      - shell: bash
        run: |
          echo 'Test upload artifact' > output.log
      - name: Upload output file
        uses: actions/upload-artifact@v2
        with:
          name: output-log-file
          path: output.log

  ci_ubuntu2204_node14:
    name: CI on Windows with Node 14
    runs-on: ubuntu-22.04
    needs: lint
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 14
      - name: Run test suite
        run: |
          echo npm ci
          echo npm run build --if-present
          echo npm test
      - shell: bash
        run: |
          echo 'Test upload artifact' > output.log
      - name: Upload output file
        uses: actions/upload-artifact@v2
        with:
          name: output-log-file
          path: output.log
          
  ci_macos_node14:
    name: CI on Windows with Node 14
    runs-on: macos-latest
    needs: lint
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 14
      - name: Run test suite
        run: |
          echo npm ci
          echo npm run build --if-present
          echo npm test
      - shell: bash
        run: |
          echo 'Test upload artifact' > output.log
      - name: Upload output file
        uses: actions/upload-artifact@v2
        with:
          name: output-log-file
          path: output.log
    
ci_windows_node16:
    name: CI on Windows with Node 16
    runs-on: windows-2019
    needs: lint
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Run test suite
        run: |
          echo npm ci
          echo npm run build --if-present
          echo npm test
      - shell: bash
        run: |
          echo 'Test upload artifact' > output.log
      - name: Upload output file
        uses: actions/upload-artifact@v2
        with:
          name: output-log-file
          path: output.log

  ci_ubuntu2004_node16:
    name: CI on Windows with Node 16
    runs-on: ubuntu-20.04
    needs: lint
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Run test suite
        run: |
          echo npm ci
          echo npm run build --if-present
          echo npm test
      - shell: bash
        run: |
          echo 'Test upload artifact' > output.log
      - name: Upload output file
        uses: actions/upload-artifact@v2
        with:
          name: output-log-file
          path: output.log

  ci_ubuntu2204_node16:
    name: CI on Windows with Node 16
    runs-on: ubuntu-22.04
    needs: lint
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Run test suite
        run: |
          echo npm ci
          echo npm run build --if-present
          echo npm test
      - shell: bash
        run: |
          echo 'Test upload artifact' > output.log
      - name: Upload output file
        uses: actions/upload-artifact@v2
        with:
          name: output-log-file
          path: output.log
          
  ci_macos_node16:
    name: CI on Windows with Node 16
    runs-on: macos-latest
    needs: lint
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Run test suite
        run: |
          echo npm ci
          echo npm run build --if-present
          echo npm test
      - shell: bash
        run: |
          echo 'Test upload artifact' > output.log
      - name: Upload output file
        uses: actions/upload-artifact@v2
        with:
          name: output-log-file
          path: output.log


  deploy-test:
    name: Deploy to test env
    runs-on: ubuntu-latest
    needs: [ci_windows_node12, ci_windows_node14, ci_windows_node16, ci_ubuntu20_node12, ...] # Include all the CI jobs here
    environment:
      name: TEST
      url: https://test.company.com
    steps:
      - name: Checkout
        uses: actions/checkout@v4