swagger: '2.0'
info:
  version: '1.0.0'
  title: 'Contacts API'
paths:
  /contacts/save:
    post:
      summary: 'Save contact'
      description: 'Save a new contact'
      consumes:
        - 'application/json'
      produces:
        - 'application/json'
      parameters:
        - in: 'body'
          name: 'body'
          description: 'Contact object that needs to be added'
          required: true
          schema:
            $ref: '#/definitions/Contact'
      responses:
        '201':
          description: 'Contact created'
        '400':
          description: 'Invalid input'
  /contacts/all:
    get:
      summary: 'Get all contacts'
      description: 'Get a list of all contacts'
      produces:
        - 'application/json'
      responses:
        '200':
          description: 'successful operation'
  /contacts/{id}:
    get:
      summary: 'Find contact by ID'
      description: 'Returns a single contact'
      produces:
        - 'application/json'
      parameters:
        - name: 'id'
          in: 'path'
          description: 'ID of contact to return'
          required: true
          type: 'integer'
          format: 'int32'
      responses:
        '200':
          description: 'successful operation'
        '404':
          description: 'Contact not found'
    delete:
      summary: 'Deletes a contact'
      description: 'Delete a contact by ID'
      parameters:
        - name: 'id'
          in: 'path'
          description: 'ID of the contact to delete'
          required: true
          type: 'integer'
          format: 'int32'
      responses:
        '200':
          description: 'Contact deleted'
        '404':
          description: 'Contact not found'
definitions:
  Contact:
    type: 'object'
    properties:
      id:
        type: 'integer'
        format: 'int64'
      name:
        type: 'string'
      phone:
        type: 'string'
